package com.que.que.Partner.PartnerChangeRequest;

public enum PartnerChangeRequestType {
    NAME,
    ADDRESS,
    PHONE_NUMBER,
    WEBSITE,
    OPENING_HOURS_MONDAY,
    OPENING_HOURS_TUESDAY,
    OPENING_HOURS_WEDNESDAY,
    OPENING_HOURS_THURSDAY,
    OPENING_HOURS_FRIDAY,
    OPENING_HOURS_SATURDAY,
    OPENING_HOURS_SUNDAY,
}
