spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://splandamedia.com/splandamedia_testDB
spring.datasource.username=splandamedia_splandamedia
spring.datasource.password=m2?GW%iQ6e[l
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fam.awad.awad@gmail.com
spring.mail.password=FamAwadisthebest123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true