version: "1"

services:
  # Database container
  database:
    container_name: queue-mysql-database
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    networks:
      - backend-network
    volumes:
      - queue_mysql_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    restart: always

  # Backend container
  backend:
    container_name: queue-springboot-backend
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy

volumes:
  queue_mysql_data:

networks:
  backend-network:
