package com.que.que.User;

public enum UserRole {
  USER,
  TAWABIRY_SYSTEM_ADMIN,
  TAWABIRY_DEVELOPER,
  TAWABIRY_SUPPORT,
  TAWABIRY_MANAGER,
  TAWABIRY_EMPLOYEE,
  BUSINESS_OWNER,
  BUSINESS_EMPLOYEE,
  BUSINESS_MANAGER,
  BUSINESS_ADMIN
}
